version: "3.4"
services:
  postgres:
    image: postgres-imagelocal
    container_name: postgres
    environment:
      POSTGRES_USER: challenge
      POSTGRES_PASSWORD: challenge
      POSTGRES_DB: challenge
    ports:
      - 5432:5432
    build:
      context: .
      dockerfile: dockerfile-postgre
    working_dir: ''
    command: ''

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    container_name: elasticsearch
    environment:
      - "xpack.security.enabled=false"
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
        - 9200:9200

  catapi-rest:
    image: catapi-image
    container_name: catapi-rest
    ports:
       - target: 5000
         published: 5000
    build:
      context: .
      dockerfile: dockerfile-api
    working_dir: ''
    command: ''
    environment:
      POSTGRES_HOST: postgres://challenge:challenge@postgres:5432/challenge
      ELASTIC_HOST: es
    links:
      - postgres
      - es

  catinvoker:
    image: catinvoker-image
    container_name: catinvoker
    build:
      context: .
      dockerfile: dockerfile-invoker
    working_dir: ''
    command: ''
    environment:
      POSTGRES_HOST: postgres://challenge:challenge@postgres:5432/challenge
    links:
      - postgres

  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: challenge
    ports:
      - 5601:5601
    links:
      - es
      
volumes:
  esdata:
    driver: local
